# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: easytospell.net
email: rgm@linux.com
author: Richard Marshall
description: > # this means to ignore newlines until "baseurl:"
  digging about the linux kernel, bad puns, and various other computer science things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.easytospell.net" # the base hostname & protocol for your site
twitter_username: richardgm42
github_username:  richardmarshall

# Build settings
markdown: kramdown
highlighter: rouge
